version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./php
    ports:
      - '9090:9000'
    volumes:
      - ./www:/var/www/slim_app

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www/slim_app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php